'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ModuleLandingPage
    
    '''<summary>
    '''lblSandbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSandbox As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlOptions As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNew As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''pnlNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNew As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''imgHelp_AcctNum_New1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp_AcctNum_New1 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ddlSearchField_New control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearchField_New As Global.UtilityWizards.CommonCore.[Shared].Controls.DropDownLists.DropDownList
    
    '''<summary>
    '''imgHelp_AcctNum_New0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp_AcctNum_New0 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txtSearch_New control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearch_New As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''btnSearch_New control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch_New As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''RadCustomerGrid_New control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCustomerGrid_New As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''pnlSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlSearch As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ddlSearchField_Existing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSearchField_Existing As Global.UtilityWizards.CommonCore.[Shared].Controls.DropDownLists.DropDownList
    
    '''<summary>
    '''Image2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txtSearch_Existing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearch_Existing As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''btnSearch_Existing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch_Existing As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btnShowAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShowAll As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''imgHelp_Customers_Existing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp_Customers_Existing As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''RadCustomerGrid_Existing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadCustomerGrid_Existing As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UtilityWizards.Builder.ContentPage
        Get
            Return CType(MyBase.Master,UtilityWizards.Builder.ContentPage)
        End Get
    End Property
End Class
