'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ModuleTab
    
    '''<summary>
    '''litNoData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litNoData As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlDataNav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDataNav As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lnkFirstRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFirstRecord As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkPreviousRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkPreviousRecord As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtRecordNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRecordNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkNextRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNextRecord As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lnkLastRecord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkLastRecord As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblTotalRecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalRecords As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlScrollModuleView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlScrollModuleView As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ModuleView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModuleView1 As Global.UtilityWizards.Builder.ModuleView
    
    '''<summary>
    '''pnlHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHidden As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtID As Global.UtilityWizards.CommonCore.[Shared].Controls.TextBoxes.TextBox
    
    '''<summary>
    '''txtUserEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserEmail As Global.UtilityWizards.CommonCore.[Shared].Controls.TextBoxes.TextBox
    
    '''<summary>
    '''txtViewed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtViewed As Global.UtilityWizards.CommonCore.[Shared].Controls.TextBoxes.TextBox
    
    '''<summary>
    '''txtCustomerServiceAddressLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerServiceAddressLat As Global.UtilityWizards.CommonCore.[Shared].Controls.TextBoxes.TextBox
    
    '''<summary>
    '''txtCustomerServiceAddressLon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerServiceAddressLon As Global.UtilityWizards.CommonCore.[Shared].Controls.TextBoxes.TextBox
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UtilityWizards.Builder.TabPage
        Get
            Return CType(MyBase.Master,UtilityWizards.Builder.TabPage)
        End Get
    End Property
End Class
