'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ModuleWizard
    
    '''<summary>
    '''pnlStep1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStep1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''imgHelp_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp_Name As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txtName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtName As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''imgHelp_Desc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp_Desc As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''ddlSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSupervisor As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''pnlModuleStep1Questions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlModuleStep1Questions As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''chkImportModule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkImportModule As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''imgHelp_Folder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp_Folder As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ddlImportTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlImportTable As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''imgHelp_Icon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp_Icon As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ddlIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlIcon As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''imgIcon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgIcon As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''pnlStep2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStep2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''imgHelp_Question control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp_Question As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ddlQuestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuestion As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''lblDataField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDataField As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''imgHelp_Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp_Type As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''ddlQuestionType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlQuestionType As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''imgHelp_Required control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp_Required As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''chkRequired control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkRequired As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''imgHelp_Search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp_Search As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''chkSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSearch As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''imgHelp_Reporting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp_Reporting As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''chkReporting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkReporting As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''imgHelp_Export control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp_Export As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''chkExport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkExport As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkMobile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkMobile As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDisplay As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ddlDisplay control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDisplay As Global.Telerik.Web.UI.RadComboBox
    
    '''<summary>
    '''txtSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSort As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''pnlDropDownValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDropDownValues As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''imgHelp_Values control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp_Values As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''txtDDLValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDDLValue As Global.Telerik.Web.UI.RadTextBox
    
    '''<summary>
    '''btnAddValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddValue As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''lstValues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstValues As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''btnRemoveValue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRemoveValue As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btnAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAdd As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''imgHelp_Preview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgHelp_Preview As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''tblModuleQuestions_TopLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblModuleQuestions_TopLeft As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''tblModuleQuestions_TopMiddle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblModuleQuestions_TopMiddle As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''tblModuleQuestions_TopRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblModuleQuestions_TopRight As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''tblModuleQuestions_FullPage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblModuleQuestions_FullPage As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''tblModuleQuestions_BottomLeft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblModuleQuestions_BottomLeft As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''tblModuleQuestions_BottomMiddle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblModuleQuestions_BottomMiddle As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''tblModuleQuestions_BottomRight control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblModuleQuestions_BottomRight As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''pnlStep3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStep3 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblModuleName1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModuleName1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlStep4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStep4 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlStep5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStep5 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlStep6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStep6 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''btnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNext As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''pnlHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHidden As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblClientID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClientID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblUserID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlStepInfo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStepInfo1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlFolderStepInfo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFolderStepInfo1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlModuleStepInfo1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlModuleStepInfo1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlStepInfo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStepInfo2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlFolderStepInfo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlFolderStepInfo2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlModuleStepInfo2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlModuleStepInfo2 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblModuleName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblModuleName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pnlStepInfo3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStepInfo3 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlStepInfo4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStepInfo4 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlStepInfo5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStepInfo5 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnlStepInfo6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlStepInfo6 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UtilityWizards.Builder.Wizard_V2
        Get
            Return CType(MyBase.Master,UtilityWizards.Builder.Wizard_V2)
        End Get
    End Property
End Class
