'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Print
    
    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''RadScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadScriptManager1 As Global.Telerik.Web.UI.RadScriptManager
    
    '''<summary>
    '''tblFolderQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFolderQuestions As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''tblModuleQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblModuleQuestions As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''lblAcctNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAcctNum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAcctNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcctNumber As Global.UtilityWizards.CommonCore.[Shared].Controls.Labels.DataLabel
    
    '''<summary>
    '''txtCustomerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerName As Global.UtilityWizards.CommonCore.[Shared].Controls.Labels.DataLabel
    
    '''<summary>
    '''lblLocationNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLocationNum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLocationNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLocationNum As Global.UtilityWizards.CommonCore.[Shared].Controls.Labels.DataLabel
    
    '''<summary>
    '''txtCustomerServiceAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerServiceAddress As Global.UtilityWizards.CommonCore.[Shared].Controls.Labels.DataLabel
    
    '''<summary>
    '''tbl811SignOff control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbl811SignOff As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''ddlStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStatus As Global.UtilityWizards.CommonCore.[Shared].Controls.Labels.DataLabel
    
    '''<summary>
    '''ddlPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPriority As Global.UtilityWizards.CommonCore.[Shared].Controls.Labels.DataLabel
    
    '''<summary>
    '''chkNotifyAdmins control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNotifyAdmins As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ddlSupervisor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSupervisor As Global.UtilityWizards.CommonCore.[Shared].Controls.Labels.DataLabel
    
    '''<summary>
    '''ddlTechnician control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTechnician As Global.UtilityWizards.CommonCore.[Shared].Controls.Labels.DataLabel
    
    '''<summary>
    '''txtTechComments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTechComments As Global.UtilityWizards.CommonCore.[Shared].Controls.Labels.DataLabel
    
    '''<summary>
    '''RadMap1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadMap1 As Global.Telerik.Web.UI.RadMap
    
    '''<summary>
    '''txtPrintView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrintView As Global.UtilityWizards.CommonCore.[Shared].Controls.Labels.DataLabel
End Class
