'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace UWAPI
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="InputControllerSoap", [Namespace]:="https://westonapi.utilitywizards.com/")>  _
    Partial Public Class InputController
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetApiKeyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UploadFileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.UtilityWizards.Builder.My.MySettings.Default.UtilityWizards_Builder_UWAPI_InputController
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetApiKeyCompleted As GetApiKeyCompletedEventHandler
        
        '''<remarks/>
        Public Event UploadFileCompleted As UploadFileCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://westonapi.utilitywizards.com/GetApiKey", RequestNamespace:="https://westonapi.utilitywizards.com/", ResponseNamespace:="https://westonapi.utilitywizards.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetApiKey(ByVal userEmail As String, ByVal userPassword As String, ByVal UseSandboxDb As Boolean) As ApiKeyResult
            Dim results() As Object = Me.Invoke("GetApiKey", New Object() {userEmail, userPassword, UseSandboxDb})
            Return CType(results(0),ApiKeyResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetApiKeyAsync(ByVal userEmail As String, ByVal userPassword As String, ByVal UseSandboxDb As Boolean)
            Me.GetApiKeyAsync(userEmail, userPassword, UseSandboxDb, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetApiKeyAsync(ByVal userEmail As String, ByVal userPassword As String, ByVal UseSandboxDb As Boolean, ByVal userState As Object)
            If (Me.GetApiKeyOperationCompleted Is Nothing) Then
                Me.GetApiKeyOperationCompleted = AddressOf Me.OnGetApiKeyOperationCompleted
            End If
            Me.InvokeAsync("GetApiKey", New Object() {userEmail, userPassword, UseSandboxDb}, Me.GetApiKeyOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetApiKeyOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetApiKeyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetApiKeyCompleted(Me, New GetApiKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://westonapi.utilitywizards.com/UploadFile", RequestNamespace:="https://westonapi.utilitywizards.com/", ResponseNamespace:="https://westonapi.utilitywizards.com/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UploadFile(ByVal req As ApiRequest, <System.Xml.Serialization.XmlElementAttribute(DataType:="base64Binary")> ByVal fData() As Byte, ByVal fName As String) As ApiResponse
            Dim results() As Object = Me.Invoke("UploadFile", New Object() {req, fData, fName})
            Return CType(results(0),ApiResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UploadFileAsync(ByVal req As ApiRequest, ByVal fData() As Byte, ByVal fName As String)
            Me.UploadFileAsync(req, fData, fName, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UploadFileAsync(ByVal req As ApiRequest, ByVal fData() As Byte, ByVal fName As String, ByVal userState As Object)
            If (Me.UploadFileOperationCompleted Is Nothing) Then
                Me.UploadFileOperationCompleted = AddressOf Me.OnUploadFileOperationCompleted
            End If
            Me.InvokeAsync("UploadFile", New Object() {req, fData, fName}, Me.UploadFileOperationCompleted, userState)
        End Sub
        
        Private Sub OnUploadFileOperationCompleted(ByVal arg As Object)
            If (Not (Me.UploadFileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UploadFileCompleted(Me, New UploadFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://westonapi.utilitywizards.com/")>  _
    Partial Public Class ApiKeyResult
        
        Private userEmailField As String
        
        Private userPasswordField As String
        
        Private apiKeyField As String
        
        Private clientIDField As Integer
        
        Private responseCodeField As ApiResultCode
        
        Private responseMessageField As String
        
        Private useSandboxDbField As Boolean
        
        '''<remarks/>
        Public Property UserEmail() As String
            Get
                Return Me.userEmailField
            End Get
            Set
                Me.userEmailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UserPassword() As String
            Get
                Return Me.userPasswordField
            End Get
            Set
                Me.userPasswordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApiKey() As String
            Get
                Return Me.apiKeyField
            End Get
            Set
                Me.apiKeyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ClientID() As Integer
            Get
                Return Me.clientIDField
            End Get
            Set
                Me.clientIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property responseCode() As ApiResultCode
            Get
                Return Me.responseCodeField
            End Get
            Set
                Me.responseCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property responseMessage() As String
            Get
                Return Me.responseMessageField
            End Get
            Set
                Me.responseMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UseSandboxDb() As Boolean
            Get
                Return Me.useSandboxDbField
            End Get
            Set
                Me.useSandboxDbField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://westonapi.utilitywizards.com/")>  _
    Public Enum ApiResultCode
        
        '''<remarks/>
        success
        
        '''<remarks/>
        failed
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://westonapi.utilitywizards.com/")>  _
    Partial Public Class ApiResponse
        
        Private responseCodeField As ApiResultCode
        
        Private responseMessageField As String
        
        Private responseObjectField As Object
        
        Private useSandboxDbField As Boolean
        
        '''<remarks/>
        Public Property responseCode() As ApiResultCode
            Get
                Return Me.responseCodeField
            End Get
            Set
                Me.responseCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property responseMessage() As String
            Get
                Return Me.responseMessageField
            End Get
            Set
                Me.responseMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property responseObject() As Object
            Get
                Return Me.responseObjectField
            End Get
            Set
                Me.responseObjectField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UseSandboxDb() As Boolean
            Get
                Return Me.useSandboxDbField
            End Get
            Set
                Me.useSandboxDbField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://westonapi.utilitywizards.com/")>  _
    Partial Public Class ApiRequest
        
        Private apiKeyField As String
        
        Private clientIdField As Integer
        
        Private deviceIdField As String
        
        Private deviceTypeField As UserPlatform
        
        Private useSandboxDbField As Boolean
        
        '''<remarks/>
        Public Property apiKey() As String
            Get
                Return Me.apiKeyField
            End Get
            Set
                Me.apiKeyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property clientId() As Integer
            Get
                Return Me.clientIdField
            End Get
            Set
                Me.clientIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property deviceId() As String
            Get
                Return Me.deviceIdField
            End Get
            Set
                Me.deviceIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property deviceType() As UserPlatform
            Get
                Return Me.deviceTypeField
            End Get
            Set
                Me.deviceTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UseSandboxDb() As Boolean
            Get
                Return Me.useSandboxDbField
            End Get
            Set
                Me.useSandboxDbField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://westonapi.utilitywizards.com/")>  _
    Public Enum UserPlatform
        
        '''<remarks/>
        Unavailable
        
        '''<remarks/>
        iPhone
        
        '''<remarks/>
        iPod
        
        '''<remarks/>
        iPad
        
        '''<remarks/>
        AndroidPhone
        
        '''<remarks/>
        AndroidTablet
        
        '''<remarks/>
        WindowsPhone
        
        '''<remarks/>
        Desktop
        
        '''<remarks/>
        Api
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub GetApiKeyCompletedEventHandler(ByVal sender As Object, ByVal e As GetApiKeyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetApiKeyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ApiKeyResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ApiKeyResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")>  _
    Public Delegate Sub UploadFileCompletedEventHandler(ByVal sender As Object, ByVal e As UploadFileCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UploadFileCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ApiResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ApiResponse)
            End Get
        End Property
    End Class
End Namespace
