'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ContentPage
    
    '''<summary>
    '''headContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents headContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''menuContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents menuContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''breadcrumbContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents breadcrumbContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''MainAjaxPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainAjaxPanel As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''lblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''pageContent_Ajax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageContent_Ajax As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''pageContent_OutsideAjax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageContent_OutsideAjax As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UtilityWizards.Builder.Dashboard
        Get
            Return CType(MyBase.Master,UtilityWizards.Builder.Dashboard)
        End Get
    End Property
End Class
