'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Wizard_V2
    
    '''<summary>
    '''wizardHeadContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wizardHeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''wizardMenuContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wizardMenuContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''wizardBreadcrumbContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wizardBreadcrumbContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''lblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''wizardContent_Ajax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wizardContent_Ajax As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''wizardInfoContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wizardInfoContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''wizardContent_OutsideAjax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents wizardContent_OutsideAjax As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
