'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DebrisTally
    
    '''<summary>
    '''lblSandbox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSandbox As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tblFolderQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblFolderQuestions As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''tblModuleQuestions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblModuleQuestions As Global.System.Web.UI.WebControls.Table
    
    '''<summary>
    '''txtEmailRecipients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmailRecipients As Global.UtilityWizards.CommonCore.[Shared].Controls.TextBoxes.TextBox
    
    '''<summary>
    '''btnSendMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendMail As Global.Telerik.Web.UI.RadButton
    
    '''<summary>
    '''pnlHidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHidden As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtID As Global.UtilityWizards.CommonCore.[Shared].Controls.TextBoxes.TextBox
    
    '''<summary>
    '''txtUserEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUserEmail As Global.UtilityWizards.CommonCore.[Shared].Controls.TextBoxes.TextBox
    
    '''<summary>
    '''txtViewed control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtViewed As Global.UtilityWizards.CommonCore.[Shared].Controls.TextBoxes.TextBox
    
    '''<summary>
    '''txtCustomerServiceAddressLat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerServiceAddressLat As Global.UtilityWizards.CommonCore.[Shared].Controls.TextBoxes.TextBox
    
    '''<summary>
    '''txtCustomerServiceAddressLon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerServiceAddressLon As Global.UtilityWizards.CommonCore.[Shared].Controls.TextBoxes.TextBox
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As UtilityWizards.Builder.Dashboard
        Get
            Return CType(MyBase.Master,UtilityWizards.Builder.Dashboard)
        End Get
    End Property
End Class
